In [42]:
#Session 3 Assignment 1
#Task 1
#Write a function to compute 5/0 and use try/except to catch the exceptions.
def dividebyzero():
    pass
# Divide by zero
try:
    x = 5 / 0

except:
        print("Error dividing by zero")
        print("this division process leads to infinity")
finally:
        print("“finally block. This clause allows defining statements that we want to execute, no matters whether the try block has raised an exception or not")


Error dividing by zero
this division process leads to infinity
“finally block. This clause allows defining statements that we want to execute, no matters whether the try block has raised an exception or not


In [1]:
#Session 3 Assignment 1
#Task 1
#2. 
#Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
 # Hint: Subject,Verb and Object should be declared in the program as shown below.

subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

# Usinglist comprehension
sentence_list = [(sub+" "+ vb + " " + ob ) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
    print (sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [8]:
#Session 3 Assignment 1
#Task 2
#1.Write a function so that the columns of the output matrix are powers of the input vector. 
import numpy as np
print('Generating a Vandermonde matrix...')

N=int(input('Enter the value of N power :'))
result_array=np.vander(np.array([1,2,3]),increasing=False)
print("Displays the matrix if increasing is false\n",result_array)
result1_array=np.vander(np.array([1,2,3]),increasing=True)
print("Displays the matrix if increasing is false\n",result1_array)


Generating a Vandermonde matrix...
Enter the value of N power :3
Displays the matrix if increasing is false
 [[1 1 1]
 [4 2 1]
 [9 3 1]]
Displays the matrix if increasing is false
 [[1 1 1]
 [1 2 4]
 [1 3 9]]
